# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X7c7_4L7MVr8o4xmTawZqWn5HlDmkBqE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, balanced_accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

file_path = "/content/HEA_Phase_Dataset_v1d.xlsx"
df=pd.read_excel(file_path, sheet_name="Table 1")
df

df=df.drop(columns=["References","Alloy_ID","Alloy","ot-Cold_Workin","uench_Pro", "Homog_Temp", "Homog_Time", "Anneal_Temp", "Anneal_Time"])
print("Columns after dropping unwanted ones:")
df

df.replace("-","NaN", inplace=True)
df

X=df.drop(columns=["Phases"], errors='ignore')
y=df["Phases"].astype(str)

X

y

categorical_cols=X.select_dtypes(include=["object"]).columns.tolist()
numerical_cols=X.select_dtypes(exclude=["object"]).columns.tolist()

categorical_cols

numerical_cols

if not numerical_cols:
  numerical_cols=[]

if not categorical_cols:
  categorical_cols=[]

for col in categorical_cols:
  X[col]=X[col].astype(str)

preprocessor=ColumnTransformer(
    transformers=[
        ("num", make_pipeline(SimpleImputer(strategy="mean"),StandardScaler()), numerical_cols),
        ("cat", make_pipeline(SimpleImputer(strategy="most_frequent"),OneHotEncoder(handle_unknown="ignore")), categorical_cols)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model=make_pipeline(preprocessor, RandomForestClassifier(n_estimators=100, random_state=42))

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_train_pred=model.predict(X_train)
y_test_pred=model.predict(X_test)

train_accuracy=accuracy_score(y_train, y_train_pred)
print("Accuracy while Training:", train_accuracy)

test_accuracy=accuracy_score(y_test, y_test_pred)
print("Accuracy while Testing:", test_accuracy)

balanced_acc = balanced_accuracy_score(y_test, y_pred)
print("Balanced Accuracy:", balanced_acc)

print("Classification Report(TRAINING):\n", classification_report(y_train, y_train_pred))

print("Classification Report(TESTING):\n", classification_report(y_test, y_test_pred))

print("Classification Report:\n", classification_report(y_test, y_pred))

conf_matrix=confusion_matrix(y_train, y_train_pred)
plt.figure(figsize=(8,6))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", xticklabels=np.unique(y_train), yticklabels=np.unique(y_train))
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix of Training set")
plt.show()

conf_matrix=confusion_matrix(y_test, y_test_pred)
plt.figure(figsize=(8,6))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", xticklabels=np.unique(y_test), yticklabels=np.unique(y_test))
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix of Testing set")
plt.show()

rf_model=model.named_steps["randomforestclassifier"]

feature_names = numerical_cols.copy()
if categorical_cols:
  feature_names += list(model.named_steps["columntransformer"].named_transformers_["cat"].named_steps["onehotencoder"].get_feature_names_out())

feature_importances = rf_model.feature_importances_

sorted_indices = np.argsort(feature_importances)[::-1]
sorted_feature_importances = feature_importances[sorted_indices]
sorted_feature_names = [feature_names[i] for i in sorted_indices]

plt.figure(figsize=(10, 12))  # Increase figure size for better readability
sns.barplot(x=sorted_feature_importances, y=sorted_feature_names, color='blue')

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Feature Importance in Random Forest Model")

plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.yticks(fontsize=10)  # Reduce font size if necessary

plt.show()

HEA_mx=df.corr(numeric_only=True)
g=sns.heatmap(HEA_mx,annot=True,cmap='seismic',square=True,fmt='.1f',cbar=True,vmin=-1,vmax=1,cbar_kws={'shrink':0.75})

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 6))
df_2dhist = pd.DataFrame({
    x_label: grp['Phases'].value_counts()
    for x_label, grp in df.groupby('Sythesis_Route')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Sythesis_Route')
_ = plt.ylabel('Phases')

