# -*- coding: utf-8 -*-
"""XGBOOST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mX_Xr7aYRdCSfa6H169R-kGdUPPXojE
"""

pip install lazypredict xgboost

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from lazypredict.Supervised import LazyClassifier
from sklearn.metrics import roc_curve, auc
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns

# Load dataset
file_path = "/content/HEA_Phase_Dataset_v1d.xlsx"  # Ensure the correct file path
df = pd.read_excel(file_path)

print("Available columns in dataset:")
print(df.columns.tolist())
df

# Define the list of columns to drop
columns_to_drop = ["References", "Alloy_ID", "Alloy", "ot-Cold_Workin", "uench_Pro",
                   "Hot-Cold_Working_HIP", "Hot-Cold_Working_HW", "Hot-Cold_Working_Unknown",
                   "Hot-Cold_Working", "Quench_Process_10 °C/min", "Quench_Process_15 °C/min",
                   "Quench_Process_20 K/min", "Quench_Process_AQ", "Quench_Process_FC",
                   "Quench_Process_Unknown", "Quench_Process_WQ", "Homog_Temp", "Homog_Time",
                   "Anneal_Temp", "Anneal_Time", "Quench_Process"]

# Drop columns if they exist in the DataFrame
df_cleaned = df.drop(columns=[col for col in columns_to_drop if col in df.columns], errors="ignore")

print("Columns after dropping unwanted ones:")
print(df_cleaned.columns.tolist())

df_cleaned

df_cleaned

# Create a copy of the cleaned DataFrame
df_encoded = df_cleaned.copy()

# Encode the target variable 'Phases'
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_encoded["Phases"] = label_encoder.fit_transform(df_encoded["Phases"])

# Define features (X) and target (y)
X = df_encoded.drop(columns=["Phases"])  # Features
y = df_encoded["Phases"]  # Target variable

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Apply Lazy Predict with XGBoost
clf = LazyClassifier(custom_metric=None, verbose=0)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

# Print model rankings
print(models)

# Convert object columns to categorical
for col in X_train.select_dtypes(include=['object']).columns:
    X_train[col] = X_train[col].astype('category')

# If needed, also apply this to X_test
for col in X_test.select_dtypes(include=['object']).columns:
    X_test[col] = X_test[col].astype('category')

# Train XGBoost Classifier separately
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss', enable_categorical=True)
xgb_model.fit(X_train, y_train)

# Get predicted probabilities for the positive class
y_prob = xgb_model.predict_proba(X_test)[:, 1]

# Compute ROC curve and AUC score
fpr, tpr, _ = roc_curve(y_test, y_prob, pos_label=1)
roc_auc = auc(fpr, tpr)

# Plot ROC Curve
plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, color='blue', lw=2, label=f'XGBoost (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')  # Random classifier line
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.show()

y_pred = xgb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Testing Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8,6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=np.unique(y_test), yticklabels=np.unique(y_test))
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix for Testing set")
plt.show()

from sklearn.metrics import classification_report

# Assuming y_test is the true labels and y_pred are your model's predictions
print("Classification Report for Testing set:\n")
print(classification_report(y_test, y_pred))

from sklearn.metrics import accuracy_score

# Predict on the training set
y_train_pred = xgb_model.predict(X_train)

# Compute training accuracy
train_accuracy = accuracy_score(y_train, y_train_pred)
print(f"Training Accuracy: {train_accuracy}")

from sklearn.metrics import balanced_accuracy_score

balanced_acc = balanced_accuracy_score(y_test, y_pred)
print("Balanced Accuracy:", balanced_acc)

# Train XGBoost model
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss', enable_categorical=True)
xgb_model.fit(X_train, y_train)

# Evaluation on Training Data
print("\n=== Evaluation on Training Data ===")
y_train_pred = xgb_model.predict(X_train)

train_accuracy = accuracy_score(y_train, y_train_pred)
print(f"Training Accuracy: {train_accuracy:.2f}")

print("\nClassification Report for Training set:")
print(classification_report(y_train, y_train_pred))

conf_matrix_train = confusion_matrix(y_train, y_train_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix_train, annot=True, fmt='d', cmap='Greens',
            xticklabels=np.unique(y_train), yticklabels=np.unique(y_train))
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix for Training Set")
plt.show()

# === LazyClassifier Comparison ===
lazy_clf = LazyClassifier(verbose=0, ignore_warnings=True)
models, predictions = lazy_clf.fit(X_train, X_test, y_train, y_test)
print(" LazyClassifier Model Comparison:")
print(models)

import xgboost as xgb
import matplotlib.pyplot as plt
import seaborn as sns

# Use the correct model name
importances = xgb_model.feature_importances_
feature_names = X_train.columns

# Sort by importance
sorted_indices = importances.argsort()[::-1]
sorted_importances = importances[sorted_indices]
sorted_features = feature_names[sorted_indices]

# Plot
plt.figure(figsize=(4, 6))
sns.barplot(x=sorted_importances, y=sorted_features, color='blue')

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Feature Importance in XGBoost Model")

plt.xticks(rotation=45)
plt.yticks(fontsize=10)

plt.tight_layout()
plt.show()

HEA_mx=df.corr(numeric_only=True)
g=sns.heatmap(HEA_mx,annot=True,cmap='seismic',square=True,fmt='.1f',cbar=True,vmin=-1,vmax=1,cbar_kws={'shrink':0.75})

from sklearn.metrics import balanced_accuracy_score

balanced_acc = balanced_accuracy_score(y_test, y_pred)
print("Balanced Accuracy:", balanced_acc)

